name: Build & Deploy (Hostinger)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Use npm ci only if you have package-lock.json; else switch to npm install
      - run: npm ci

      - run: npm run build   # Next exports to /out

      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: out
          path: out

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}      # e.g. 145.79.210.250
          username: ${{ secrets.FTP_USERNAME }}  # e.g. u978435443
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: out/
          server-dir: public_html/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            .htaccess
