name: Build & Deploy (Hostinger)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # swap to `npm install` if you don't have package-lock.json
      - run: npm ci || npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: out
          path: out

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: out/
          server-dir: public_html/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            .htaccess
